<?php


		
echo $html ='<div class="Montserrat-Light text-color-web">
    <!--start section1-->
    <div class="container-fluid "><br>
        <div class="row">
            <div class="col-12 col-md-12 col-lg-6  pr-lg-0 pl-lg-5"data-aos="fade-right"
     data-aos-offset="300"
     data-aos-easing="ease-in-sine">
                <img src="https://www.escuelaelda.com/img/escuela.PNG" class="img-fluid float-lg-right w-100" alt="Responsive image">
            </div>
            <div class="col-12  col-md-12 col-lg-5 pl-3 pl-lg-5" style="padding-left: 5em;">
                <br>
                <h3 class="Montserrat-Bold">¿Qué es ELDA?</h3>
                <hr style="border:1px solid #888787 !important; margin-top: 10px;">
                <p class="text-justify" style="font-size: 14px;">
                    La Escuela Latinoamericana de Agricultura es una institución creada por personal con vasta experiencia en el sector educación y sector agrícola. Con el fin de contribuir en el crecimiento, modernización y uso de buenas prácticas en la industria agrícola.
                </p><hr class="bg-light d-md-none">
            </div>
        </div>
    </div>
    <!--end section1--->

    <!--start section2-->
    <div class="container pt-2 pt-md-5">
        <div class="row">
            <div class="col-sm-12 col-md-6 pr-3 pr-md-5" style="border-right: 1px solid #888787 !important;">
                <div class="float-right">
                    <h4 class="Montserrat-SemiBold"><img src="https://www.escuelaelda.com/img/mision.PNG" class="img-fluid" alt="mision"
                                                         style="padding-right: 0.2em;width: 76px;">Misión</h4>

                    <p class="text-justify pt-2" style="font-size: 14px;">
                        Contribuir con el desarrollo del sector agrícola en el Perú y Latinoamérica. A través de la capacitación del factor
                        humano que es parte de la cadena de valor, con programas educativos de alta especialización en agricultura.
                    </p>
                </div>
            </div>
            <div class="col-sm-12 col-md-6  pl-3 pl-md-5">

                <h4 class="Montserrat-SemiBold"><img src="https://www.escuelaelda.com/img/vision.PNG" class="img-fluid" alt="vision"
                                                     style="padding-right: 0.2em;width: 76px;">Visión</h4>

                <p class="text-justify pt-2" style="font-size: 14px;">
                    Ser la primera institución en Latinoamérica y el mundo que logre revalorizar la importancia de la agricultura como una actividad no sólo económica, sino una actividad que involucra esfuerzo, pasión, orgullo y ética. Una industria completamente involucrada con el factor humano, desde el agricultor hasta la gran empresa, y que sirve como agente de cambio para el medio ambiente.
                </p>
            </div>
        </div>
    </div>


    <!--end section2--->

    <!--start jumbotron1-->
    <br><br><br>
    <div class="jumbotron jumbotron-fluid text-center sobre_escuela_ban1" style="padding-top: 2rem;padding-bottom: 2rem;background-image: url(https://www.escuelaelda.com//img/escuela_banner_1.png) !important;">
        <div class="container">

            <p class="lead Montserrat-Light"  data-aos="flip-left" data-aos-easing="ease-out-cubic"data-aos-duration="2000" style="color:white;font-size: 16px;">La Escuela ha formado una propuesta de valor basada, en la <span class="lead Montserrat-SemiBold"  style="font-size: 16px;">identificación de las necesidades estrátegicas sectoriales</span>, a partir de las cuales se definen la <span class="lead Montserrat-SemiBold"  style="font-size: 16px;">competencias requeridas</span> por el sector agrícola. Con el fin, de diseñar <span class="lead Montserrat-SemiBold"  style="font-size: 16px;">programas de formación</span> a la medida de las necesidades de la industria.
            </p>
        </div>
    </div>
    <!--end jumbotron1-->


    <!-- start program desktop--->
 ';
        




/*SELECT 
		*
			FROM edu_articulo EA
			WHERE   EA.Fecha_Inicio_R BETWEEN '2020-10-01' AND '2020-11-01'*/	
		
?>