<?php

$Redirect = "";	
        $Redirect = "";
        $Entity = $viewDataArray["Id_Entity"];
        $empresa = $viewDataArray['Url'];
		$Id_Object = $viewDataArray["Id_Object"];
		$Id = $viewDataArray["Id_Hash"];
        $IdForm = "Obj_Password_Reset_Process";	
        $IdButton = "button_animatedModal5";	
	
        $Direcction = $UrlFile.$Redirect."/Process/ENTRY/Obj/".$IdForm."/empresa/".$empresa."/Id/".$Id;	
       
 
        $Screen = "Msg_0";	
        $Class = "btn btn-info btn-block";	
		$NameButton = "Recuperar Contraseña";
		$Html = '
			<div class="authentication-content m-b-30" id="panel_formulario">
                <h3 class="m-t-0 m-b-30 text-center">Introducir nueva contraseña</h3>
                <br>
            <form id="'.$IdForm.'" action="javascript:void(null);"  enctype="multipart/form-data" >	
                <div class="row">
                    <div class="container">
				        <div class=" form-group   text-center">
                                    <label for="form-control-1" class="control-label"><b>Nueva Contraseña<b></label>  
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">               
                                    <input style="margin-left:50%;" type="password" name="password" class="form-control " id="form-control-1" placeholder="Nueva Contraseña" >
                                    </div>
                        </div>
                        <div class=" form-group  text-center">
                                    <label for="form-control-1" class="control-label">Repetir Contraseña</label>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <input style="margin-left:50%;" type="password" name="password_b" class="form-control" id="form-control-1" placeholder="Repetir Contraseña" >
                                    </div>
                        </div>
                                <div>
                                <button type="submit" onclick=SaveForm(this); direction="/recuperar-password'.$Direcction.'" screen="'.$Screen.'"  class="'.$Class.'"  id="'.$IdButton.'" form="'.$IdForm.'"  >'.$NameButton.'</button>
                                </div>
                        
                    </div>
                </div>
                <br>
            </form>
	<div id="Msg_0">
            </div>
            
	    ';

		echo $Html;
	