  <!--Page Title-->
        <section class="page-title" style="background-image:url(simages/background/page-title-1.jpg);">
            <div class="auto-container">
                <h1>SOMOS</h1>
            </div>
        </section>
        <!--Page Title end-->

        <!--Page Info-->
        <section class="page-info">
            <div class="auto-container clearfix">
                <div class="pull-left">
                    <h3></h3>
                </div>
                <div class="pull-right">
                    <ul class="bread-crumb clearfix">
                        <li><a href="/">Inicio</a></li>
                        <li>Somos</li>
                    </ul>
                </div>
            </div>
        </section>
        <!--Page Info end-->

        <!--about-section-->
        <section class="about-section sec-padding">
            <div class="container">
                <div class="row">
                    <div class="col-sm-5">
                        <div class="left-side">
                            <img src="simages/resource/businessman-2.png" />
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="right-side">
                            <h4>Tu éxito es<span class="p-color"> NUESTRO </span> éxito</h4>
                            <h5>Nos ponemos a tu disposición para enfrentar juntos los retos de un Mercado Globalizado </h5>
                            <p>
							Standard Business, es una empresa que nace con la misiva de Asesorar, Capacitar,
							Innovar y brindar Herramientas de primer orden a las empresas con una visión de liderazgo, globalización y competitividad.
							
							El mercado global impone grandes retos para cada empresa que busca ser una MARCA Diferente y Competitiva en su sector; Por ello nos 
							hemos trasado la meta de desarrollar servicios innovadores, con estándares internacionales y de bajo costo, 
							soportados por un gran staff de profesionales y consultores asociados que poseen amplia experiencia en los mercados Nacionales e Internacionales en 
                            los diversos rubros del sector Empresarial y Gubernamental.
							
							</p>
                            <br/>
                            <cite>Standard Business </cite>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--about-section end-->

	    <?=$Indicadores;?>
		<!-- fact counter end -->
		

        <!-- Testimonial -->
		<?=$Testimonial;?>       

        <!-- Testimonial -->
		<?=$Clients;?>       

		<style>
		#Clientes img{
			transform-style: preserve-3d;
			width: 143px;
			margin: 59px 0px 0px 0px;			
		}
		</style>