       

        <!--Partener slider -->
        <section class="parterer-sec">
            <div class="auto-container">
			    <br>
			    <br>
			    <br>
                <div class="sec-title text-center">
				    <h2>Clientes</h2>
                    <p>Empresas vinculadas a nuestros consultores y empresas asociadas</p>
                    <span class="colorborder"></span>
                </div>
							
                <div class="partener-slider" id="Clientes">
                    <div class="image-box">
                        <a href="#"><img src="simages/clients/11.png" alt=""></a>
                    </div>
                    <div class="image-box">
                        <a href="#"><img src="simages/clients/3.png" alt=""></a>
                    </div>
                    <div class="image-box">
                        <a href="#"><img src="simages/clients/4.png" alt=""></a>
                    </div>
                    <div class="image-box">
                        <a href="#"><img src="simages/clients/10.png" alt=""></a>
                    </div>
                    <div class="image-box">
                        <a href="#"><img src="simages/clients/7.png" alt=""></a>
                    </div>
                    <div class="image-box">
                        <a href="#"><img src="simages/clients/8.png" alt=""></a>
                    </div>
                    <div class="image-box">
                        <a href="#"><img src="simages/clients/9.png" alt=""></a>
                    </div>
                    <div class="image-box">
                        <a href="#"><img src="simages/clients/12.png" alt=""></a>
                    </div>
                    <div class="image-box">
                        <a href="#"><img src="simages/clients/13.png" alt=""></a>
                    </div>					
                    <div class="image-box">
                        <a href="#"><img src="simages/clients/14.png" alt=""></a>
                    </div>					
										
                </div>
            </div>
        </section>
        <!--Partener slider end-->
		