        <!--Page Title-->
        <section class="page-title" style="background-image:url(simages/background/page-title-6.jpg);">
            <div class="auto-container">
                <h1>CONTÁCTANOS</h1>
				<p style="color: #b9b4b4;">Es un agrado para nosotros escuchar tus consultas y ayudarte a tomar la mejor desición
				</p>
            </div>
        </section>
        <!--Page Title end-->

        <!--Page Info-->
        <section class="page-info">
            <div class="auto-container clearfix">
                <div class="pull-left">
                    <h3></h3>
                </div>
                <div class="pull-right">
                    <ul class="bread-crumb clearfix">
                        <li><a href="/">Inicio</a></li>
                        <li>Contáctanos</li>
                    </ul>
                </div>
            </div>
        </section>
        <!--Page Info end-->

        <!-- contect-page-section -->
        <section class="contact-section">
            <div class="auto-container">
                <div class="row clearfix">
                    <!--Column-->
                    <div class="column col-md-7 col-sm-6 col-xs-12">
                        <h2>Escríbenos tu Consulta</h2>
						<div id="Message"></div>
                        <div class="contact-form default-form">
                            <form method="post" id="Form_Call" action="javascript:void(null);" url="/contact/Transaction/INSERT/Form/Form_Call" >
                                <div class="row">
                                    <div class="col-md-6 col-sm-12">
                                        <div class="form-group">
                                            <input name="username" value="" placeholder="Nombres" type="text">
                                        </div>
                                    </div>

                                    <div class="col-md-6 col-sm-12">
                                        <div class="form-group">
                                            <input name="email" value="" placeholder="Email" type="email">
                                        </div>
                                    </div>

                                    <div class="col-md-12 col-sm-12">
                                        <div class="form-group">
                                            <input name="phone" value="" placeholder="Teléfono" type="text">
                                        </div>
                                    </div>

                                    <div class="col-md-12 col-sm-12">
                                        <div class="form-group">
                                            <textarea name="message" placeholder="Mensaje"></textarea>
                                        </div>
                                    </div>

                                    <div class="col-md-12 col-sm-12">
                                        <button type="submit" class="btn-one" id="Btn_Submit_form_call">ENVIAR</button>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>

                    <!--Column-->
                    <div class="column col-md-5 col-sm-6 col-xs-12">
                        <div class="inner-box">
            
                            <div class="text">
                            
							</div>

                            <div class="contact-info">
                                <ul>
                                    <li>
                                        <span class="icon flaticon-placeholder"></span>
                                        <h3>Dirección</h3> Las Artes 546 - San Borja
                                    </li>
                                    <li>
                                        <span class="icon flaticon-envelope-1"></span>
                                        <h3>Email</h3> Informes@Standardbusiness.Us
                                    </li>
                                    <li>
                                        <span class="icon flaticon-phone-call"></span>
                                        <h3>Teléfono</h3> (+051) 986 992 404
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>
        <!-- contect-page-section end -->

        <!--google map-->
        <div class="map">
            <div class="google-map" id="contact-google-map" style="height:535px; width:100%;"></div>
        </div>
        <!--google map end-->
		
		
		    <!--Scroll to top-->
    <div class="scroll-to-top scroll-to-target" data-target=".site-header"><span class="icon fa fa-long-arrow-up"></span></div>


    <!-- google map -->
   <!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAVqpxmFOFNpGasvwrqs8hOHaHaTEGpYvI"></script>-->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAHzPSV2jshbjI8fqnC_C4L08ffnj5EN3A"></script>
    <script src="sbookstores/js/gmap.js"></script>


    <!-- script JS  -->
	<script src="/sbookstores/js/home.js"></script>