		
		<div id="bd">

		 	 <div class="container">
				<div class="row">
					<div class="col-xs-4 col-sm-2">
						<div id="logo">
							<img width="50%" src="/_imagenes/usuarios/<?=$reg_datos_Servicio->ImagenLogo; ?>">
						</div>
					</div>
					<div class="col-xs-8 xol-sm-10">
						<h2 class="finish">HAZ FINALIZADO CON ÉXITO</h2>
						<h4 class="bb1-grey">la encuesta de la empresa</h4>
					</div>
				</div><!--/.row-->
			</div><!--/.container-->


			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<div class="finish-wrapper" style="height: 329px;">
							<div>
								<div class="box-grey-white">
									<div>
										<img src="/_imagenes/indications.jpg">
									</div>
									<div>
									¡Gracias! <span><?=$reg_datos_usuario->Nombre ?></span>,
									<br>
									por participar de nuestra
									Encuesta.
									</div>
								</div>

							</div>
						</div>
					</div>
				</div><!--/.row-->
			</div><!--/.container-->


		</div><!--/.bd-->
	