<div class="authentication-header m-b-30">
        <div class="clearfix">
          <div class="pull-left">
            <a class="authentication-logo" href="index.html">
              <img src="/sadministrator/simages/<?php echo $viewDataArray->Logo_Externo; ?>" alt="" height="">
           
            </a>
          </div>
          <div class="pull-right">
            <a href="http://big-bang-studio.com/pages-signup.html" class="btn btn-outline-info">Sign up</a>
          </div>
        </div>
</div>