        <section class="fact-counter-section">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-6">
                        <div class="single-fact-counter clearfix">
                            <div class="text-box">
                                <div class="icon-box">
                                    <i class="fa fa-users"></i>
                                </div>
                                <span class="number">
									<span class="timer" data-from="50" data-to="200" data-speed="5000" data-refresh-interval="50">200</span>+
                                </span>
                                <p>CONSULTORES</p>
                            </div>

                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="single-fact-counter clearfix">
                            <div class="text-box">
                                <div class="icon-box">
                                    <i class="fa fa-smile-o"></i>
                                </div>
                                <span class="number">
									<span class="timer" data-from="5" data-to="20000" data-speed="5000" data-refresh-interval="50">30000</span>+
                                </span>
                                <p>BENEFICIARIOS DE NUESTROS PROYECTOS</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="single-fact-counter clearfix">
                            <div class="text-box">
                                <div class="icon-box">
                                    <i class="fa fa-clone"></i>
                                </div>
                                <span class="number">
									<span class="timer" data-from="10" data-to="120" data-speed="5000" data-refresh-interval="50">120</span>+
                                </span>
                                <p>PROYECTOS FINALIZADOS</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="single-fact-counter clearfix bdrn">
                            <div class="text-box">
                                <div class="icon-box">
                                    <i class="fa fa-trophy"></i>
                                </div>
                                <span class="number">
									<span class="timer" data-from="5" data-to="20" data-speed="5000" data-refresh-interval="50">20</span>+
                                </span>
                                <p>CERTIFICACIONES</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>