<div class="row app-container">
    <div class="col-xs-12">
        <br>
        <br>
        <div class="center-block shopping-cart-center-block">
            <div class="row shopping-cart-product-list"   >
                <div class="col-xs-12">
                    <h3 class="text-uppercase"><strong>Información de pago</strong></h3>
                    <br>
                    <br>
                    <div class="row checkout-line">
                        <div class="col-xs-12">
                            <div class="row" id="msj_proceso">	    
							</div>
                            <div class="row">
                                <div class="col-xs-4 checkout-step completed text-center">
                                    <div class="progress">
                                        <div class="progress-bar"></div>
                                    </div>
                                    <a href="/carrito-compras/entidad/<?=$empresa; ?>/pedido/<?=$pedido; ?>" class="checkout-step-circle"><strong>1</strong></a>
                                    <span>Verifica tus datos</span>
                                </div>
                                <div class="col-xs-4 checkout-step active text-center">
                                    <div class="progress">
                                        <div class="progress-bar "></div>
                                    </div>
                                    <a href="/informacion-pago/entidad/<?=$empresa; ?>/pedido/<?=$pedido; ?>" class="checkout-step-circle"><strong>2</strong></a>
                                    <span>Información de pago</span>
                                </div>
                                <div class="col-xs-4 checkout-step  text-center">
                                    <div class="progress">
                                        <div class="progress-bar"></div>
                                    </div>
                                    <a class="checkout-step-circle"><strong>3</strong></a>
                                    <span>¡Listo!</span>
                                </div>
                            </div>

                        </div>
                    </div>
                    <br>
                    <br>

                    <form class="row" method="post" action='javascript:void(null);'  enctype='multipart/form-data' id="formularioDatosFacturacion" >
                        <div class="col-xs-12 col-sm-6">

                            <div class="row">
                                <div class="col-xs-12">
                                    <h4><strong>Datos de facturación</strong></h4>
									
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <input type="text" name="nroDocumento"  id="nroDocumento"  class="form-control" value="<?= $datosUser->NroDocumento; ?>" placeholder="DNI o RUC">
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <input type="text" name="nombre" id="nombre"  class="form-control" value="<?= $datosUser->Nombre; ?>" placeholder="Razón social" >
                                    </div>
                                </div>
								
                                <div class="col-xs-12">
                                    <div class="form-group">
									    <?php
										    if($datosUser->Email ==""){
												$readonly = "";
											}else{
												$readonly = "readonly";												
											}
										?>
                                        <input type="text" name="email" id="email" class="form-control" value="<?= $datosUser->Email; ?>" placeholder="Email"  <?=$readonly; ?>>
                                    </div>
                                </div>
								
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <input type="text" name="telefono" id="telefono" class="form-control" value="<?= $datosUser->Telefono; ?>" placeholder="Teléfono"  >
                                    </div>
                                </div>
																										
								
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <h4><strong>Dirección de facturación</strong></h4>
                                </div>
								<div id="MensajeId">
                                  
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <input type="text" name="street" id="street" class="form-control" placeholder="Calle" value="<?=$datosUltimoPedido->Direccion; ?>">
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <input type="text" name="city" id="city" class="form-control" placeholder="Ciudad" value="<?=$datosUltimoPedido->Ciudad; ?>">
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <input type="text" name="province" id="province"  class="form-control" placeholder="Provincia" value="<?=$datosUltimoPedido->Provincia; ?>">
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <input type="text" name="postalCode" id="postalCode" class="form-control" placeholder="Código postal" value="<?=$datosUltimoPedido->CodigoPostal; ?>">
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <input type="text" name="country" id="country"  class="form-control" placeholder="País" value="<?=$datosUltimoPedido->Pais; ?>">
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <input type="checkbox" name="terminos"  id="terminos" checked="true" id="terms-conditions">
                                        <label for="terminos" style="color:#000;">Acepto los <a href="/terminos-condiciones/entidad/<?=$empresa; ?>" target="_blank">términos y condiciones</a></label>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="col-xs-12 col-sm-6">

                            <div class="row">
                                <div class="col-xs-12">
                                    <h4><strong>Datos de envío</strong></h4>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <input type="radio" checked="true" id="envio" name="envio">
                                        <label for="envio" style="color:#000;">Enviar a la misma dirección de facturación</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <h4><strong>Confirmar Pago</strong></h4>
                                </div>
                            </div>
							
                            <div class="row">
			
                                <div class="col-xs-12 text-right">
                                    <br>
                                    <div class="form-group">
										<?php
										    // var_dump($detallePedido);
										    $totPedido = 0;
										    $totCantidad = 0;
											foreach ($detallePedido as $key => $reg) {
												$totPedido += $reg->Precio;
												$totCantidad += $reg->Cantidad;
												$Estado = $reg->Estado;
												$CodigoPedido = $reg->CodigoPedido;
					                            if($reg->Moneda == "Soles"){ $simboloMoneda = "S/. "; }else{ $simboloMoneda= "$ "; }
											}
										?>	
										
									    <?php if($Estado == "Cerrado" || $Estado == "EnProceso" ){ ?>
                                            <strong style="color: #f1f5f1;background-color: #F44336;padding: 3% 21%;">EL PEDIDO YA NO PUEDE SER EDITADO</strong>									
									    <?php }else{ ?>
										    <button type="submit" class="btn btn-sell"  id="botonConfirmarB">
                                            <strong>PAGAR <?=$simboloMoneda ."  ".$totPedido; ?> EN <?=$totCantidad; ?>  ARTÍCULOS</strong>
                                            </button>

                                        
									    <?php } ?>
                                      
                                    </div>
                                </div>
                            </div>

                        </div>
                    </form>

                </div>
            </div>

            <br>
            <br>
            <br>

        </div>
    </div>
</div>

<script src="https://checkout.culqi.com/plugins/v2/"></script>

<script>  
   var mensaje = "<?= $mensaje; ?>";
    if( mensaje == "error"){
		// alert("ajajaj");
		 alertify.success("No hemos podido hacer el cargo en su tarjeta, revise los datos e intente nuevamente.");	
	}
   	
	Culqi.publicKey = '<?= $publicKey; ?>';

	Culqi.settings({
	    title: 'Mi Comercio', 
	    currency: 'USD',
	    description: 'Pago de matrícula',
	    amount: 200
	});

	// Recibimos Token del Culqi.js
	function culqi() {

		if (Culqi.token) {
		  // Imprimir Token
		  console.log(Culqi.token.id);
		}

		else{
		  // Hubo un problema...
		  // Mostramos JSON de objeto error en consola
		  console.log(Culqi.error);
		  alert(Culqi.error.message);
		}

	};

	// Tratando respuesta con AJAX (jQuery)
	// alert("ahahaha");
	function culqi() {

		if(Culqi.error){
		   // Mostramos JSON de objeto error en consola
		   console.log(Culqi.error);

		   alert(Culqi.error.message);
		}
		else{
		   $.post("/system/_vistas/se_pedidos.php?Main=GenerarPago&entidad=<?php echo $empresa; ?>&pedido=<?php echo $pedido; ?>", // Ruta hacia donde enviaremos el token vía POST
		   { token: Culqi.token.id },
			function(data, status){
				if (status=="success") {
					
						var parametros = {
						};	  
							
						var ruta = "/system/_vistas/se_pedidos.php?Main=CerrarPedido&entidad=<?php echo $empresa; ?>&pedido=<?php echo $pedido; ?>";
						$.ajax({
							data: parametros,
							url: ruta,
							type: 'get',
							async: true,
							success: function(response) {
								
								if( response == "TRUE"){
									location.href="/pago-finalizado/pedido/<?php echo $pedido; ?>/entidad/<?php echo $empresa; ?>";
								}else{
									location.href="/informacion-pago/pedido/<?php echo $pedido; ?>/entidad/<?php echo $empresa; ?>/mensaje/error";
								}
						   }
						});	
		
				} else {
					
				}
			});
		   }
	};
	
</script>
<script type="text/javascript">

    $(document).ready(function(){	

	
	
		function resetPopup() {
		$("#toggleCSS").attr("href", "../themes/alertify.default.css");
		alertify.set({
			labels : {
				ok     : "Ok"
			},
			delay : 5000,
			buttonReverse : false,
			buttonFocus   : "ok"
		});
		}	

		$("#formularioDatosFacturacion").validate({

			rules: {
				nombre: { required: true, minlength: 2},
				nroDocumento: { required: true, minlength: 2},
				email: { required:true, email: true},
				telefono: { required: true,minlength: 2, maxlength: 15 },
				street: { required: true,minlength: 2},
				city: { required: true,minlength: 2},
				province: { required: true,minlength: 2},
				postalCode: { required: true,minlength: 2},
				country: { required: true,minlength: 2}
				// terminos: { required: true,minlength: 2},
				// envio: { required: true,minlength: 2},
				// cardNumber: { required: true,minlength: 2, number: true},
				// month: { required: true},
				// year: { required: true},
				// cvv: { required: true,minlength: 2},
				// nameCard: { required: true,minlength: 2}
			},
			messages: {
				nombre: "Debe introducir su nombre.",
				nroDocumento: "Debe introducir su nro. de Identficación",
				email: "Debe introducir un email válido.",
				telefono: "Debe introducir un nro. válido.",
				street: "Debe introducir su dirección.",
				city: "Debe llenar el campo.",
				province: "Debe llenar el campo.",
				postalCode: "Debe llenar el campo.",
				country: "Debe llenar el campo."
				// terminos: "Debe seleccionar la opción",
				// envio: "Debe seleccionar la opción",
				// cardNumber: "Debe llenar el campo con un valor numérico",
				// month: "Debe llenar el campo.",
				// year: "Debe llenar el campo.",
				// cvv: "Debe llenar el campo.",
				// nameCard: "Debe llenar el campo."
			},
			submitHandler: function(form){

				resetPopup();
				alertify.alert('<div id="panelPopup"><div class="preloader"><div class="status"><div class="status-mes"><h4></h4></div></div></div></div>');


				$.ajax({
					type:"POST",
					url:"/system/_vistas/se_pedidos.php?Main=ProcesarPedido&entidad=<?php echo $empresa; ?>&pedido=<?php echo $pedido; ?>",
					data: $("#formularioDatosFacturacion").serialize(), 
					success: function(data){
						
						$("#panelPopup").html("Procesando");
						
						if(data=="TRUE"){
							
							$("#alertify-cover").remove();
							$("#alertify").remove();							
						 	Culqi.open();
							e.preventDefault();
							
						}else{		
                            						
						}
						
					}
				});
			}
		});
    });

</script>