        <!-- team-section -->
        <section class="ourteamsec sec-padding">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="sec-title text-center">
                            <h2>Staff de Consultores</h2>
                            <p>Tenemos un selecto staff de consultores con amplia experiencia en el mercado Nacional e Internacional.</p>
                            <span class="colorborder"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 col-md-3 col-lg-3">
                        <div class="team-box">
                            <div class="team-head">
                                <img src="simages/resource/marcelaB.jpg" class="img-responsive mauto" alt="">
                             
                            </div>
                            <div class="team-content">
                                <h3>Marcela Injoque</h3>
                                <b>Estrategía y Capacitación</b>
                                <p>Experta en Planeamiento Estratégico, Gestión del Conocimiento, Gestión y Desarrollo del Talento. 
								Posee una vasta experiencia de 45 años en el mercado local e internacional. </p>
                                <!-- end team-social -->
                            </div>
                            <!-- end team-content -->
                        </div>
                        <!-- end team-box -->
                    </div>
                    <div class="col-sm-6 col-md-3 col-lg-3">
                        <div class="team-box">
                            <div class="team-head">
                                <img src="simages/resource/ivan_mak2.jpg" class="img-responsive mauto" alt="">

                            </div>
                            <div class="team-content">
                                <h3>Ivan Mak</h3>
                                <b>Tecnología e Innovación </b>
                                <p>Experto en informática y automatización; Posee amplia experiencia en la industria de 
								SOFTWARE y desarrollo de aplicaciones móviles, web  y UI / UX.   </p>
                                <!-- end team-social -->
                            </div>
                            <!-- end team-content -->
                        </div>
                        <!-- end team-box -->
                    </div>
                    <div class="col-sm-6 col-md-3 col-lg-3">
                        <div class="team-box">
                            <div class="team-head">
                                <img src="simages/resource/team3.jpg" class="img-responsive mauto" alt="">
                                <div class="social">
                                    <ul>
                                        <li class="facebook-icon">
                                            <a href="#">
                                                <span class="fa fa-facebook"></span>
                                            </a>
                                        </li>
                                        <li class="twitter-icon">
                                            <a href="#">
                                                <span class="fa fa-twitter"></span>
                                            </a>
                                        </li>
                                        <li class="linkedin-icon">
                                            <a href="#">
                                                <span class="fa fa-linkedin"></span>
                                            </a>
                                        </li>
                                        <li class="dribbble-icon">
                                            <a href="#">
                                                <span class="fa fa-dribbble"></span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="team-content">
                                <h3>Kathryn D. Grace</h3>
                                <b>HR Manager</b>
                                <p>Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet. </p>
                                <!-- end team-social -->
                            </div>
                            <!-- end team-content -->
                        </div>
                        <!-- end team-box -->
                    </div>
                    <div class="col-sm-6 col-md-3 col-lg-3">
                        <div class="team-box">
                            <div class="team-head">
                                <img src="simages/resource/HeribertoB.jpg" class="img-responsive mauto" alt="">
                           
                            </div>
                            <div class="team-content">
                                <h3>HERIBERTO LINARES</h3>
                                <b>Marketing y Ventas</b>
                                <p>Profesional con amplia experiencia en el desarrollo y ejecución de estrategias de Marketing
								y Ventas, aplicadas 
								en empresas trasnacionales de alto prestigio y reconocimiento.  </p>
                                <!-- end team-social -->
                            </div>
                            <!-- end team-content -->
                        </div>
                        <!-- end team-box -->
                    </div>
                </div>
            </div>
        </section>
        <!-- team section end -->