 <section class="saleofweeek">
            <div class="container">
                <div class="sec-title ltproject">
                    <h2>Últimos Proyectos</h2>
                </div>

                <div class="sowbox">
                    <div class="switem">
                        <a href="#">
                            <img src="simages/gallery/fuerza-de-ventas.jpg" />
                            <div class="swhoverbox">
                                <h3>Capacitación - Fuerza de Ventas</h3>
                            </div>
                        </a>
                    </div>

                    <div class="switem">
                        <a href="#">
                            <img src="simages/gallery/normas-iso.jpg" />
                            <div class="swhoverbox">
                                <h3>Certificación ISO</h3>
                            </div>
                        </a>
                    </div>
                    <div class="switem">
                        <a href="#">
                            <img src="simages/gallery/3.jpg" />
                            <div class="swhoverbox">
                                <h3>Diseño de Procesos</h3>
                            </div>
                        </a>
                    </div>
                    <div class="switem">
                        <a href="#">
                            <img src="simages/gallery/seguridad.jpg" />
                            <div class="swhoverbox">
                                <h3>Seguridad Informática</h3>
                            </div>
                        </a>
                    </div>
                    <div class="switem">
                        <a href="#">
                            <img src="simages/gallery/software.jpg" />
                            <div class="swhoverbox">
                                <h3>Desarrollo de Software</h3>
                            </div>
                        </a>
                    </div>
					
                    <div class="switem">
                        <a href="#">
                            <img src="simages/gallery/servidor.jpg" />
                            <div class="swhoverbox">
                                <h3>Implementación de DATA CENTER</h3>
                            </div>
                        </a>
                    </div>					
					
                </div>
            </div>
        </section>