
        <!--All Services-->

        <div class="services-sec">
            <div class="container">
				
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                        <div class="single-servicebox">
                            <div class="servicebox-image">
                                <a class="lightbox-image" data-fancybox="gallery" href="simages/services/service1.jpg">
                                    <img src="simages/services/service1.jpg" />
                                    <div class="mask"><i class="fa fa-search"></i></div>
                                </a>
                            </div>
                            <div class="servicebox-content">
                                <h3><a href="business-consulting.html">MARKETING Y VENTAS</a></h3>
                                <p>Análisis, Diagnóstico, Planificación y Ejecución de Estrategías en Marketing y Ventas.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                        <div class="single-servicebox">
                            <div class="servicebox-image">
                                <a class="lightbox-image" data-fancybox="gallery" href="simages/services/taxation.jpg">
                                    <img src="simages/services/taxation.jpg" />
                                    <div class="mask"><i class="fa fa-search"></i></div>
                                </a>
                            </div>
                            <div class="servicebox-content">
                                <h3><a href="taxation.html">GESTIÓN FINANCIERA Y CONTABLE</a></h3>
                                <p>Análisis, Diagnóstico, Planificación, Ejecución y Seguimiento de los diversos procesos Financieros y Contables.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                        <div class="single-servicebox">
                            <div class="servicebox-image">
                                <a class="lightbox-image" data-fancybox="gallery" href="simages/services/legal-corporativo.jpg">
                                    <img src="simages/services/legal-corporativo.jpg" />
                                    <div class="mask"><i class="fa fa-search"></i></div>
                                </a>
                            </div>
                            <div class="servicebox-content">
                                <h3><a href="investment-planning.html">GESTIÓN LEGAL CORPORATIVA</a></h3>
                                <p>Constituciones de sociedades, Asesoría publico privada, Propiedad Intelectual, Patentes, Acciones y Análisis de organizaciones societarias.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                        <div class="single-servicebox">
                            <div class="servicebox-image">
                                <a class="lightbox-image" data-fancybox="gallery" href="simages/services/retirementplanning.jpg">
                                    <img src="simages/services/retirementplanning.jpg" />
                                    <div class="mask"><i class="fa fa-search"></i></div>
                                </a>
                            </div>
                            <div class="servicebox-content">
                                <h3><a href="retirement-planning-2.html">GESTIÓN DE RECURSOS HUMANOS</a></h3>
                                <p>Prestraciones, Contratación, Nómina, Riesgos Laborales, Régimenes Laborales, Contigencias, Despidos y Reclamaciones.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                        <div class="single-servicebox">
                            <div class="servicebox-image">
                                <a class="lightbox-image" data-fancybox="gallery" href="simages/services/lowyerconsulting.jpg">
                                    <img src="simages/services/lowyerconsulting.jpg" />
                                    <div class="mask"><i class="fa fa-search"></i></div>
                                </a>
                            </div>
                            <div class="servicebox-content">
                                <h3><a href="lowyer-consulting.html">OPERACIONES Y PRODUCCIÓN</a></h3>
                                <p>Evaluación, diseño, planificación y ejecución de mejoras en los procesos de operaciones.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                        <div class="single-servicebox">
                            <div class="servicebox-image">
                                <a class="lightbox-image" data-fancybox="gallery" href="simages/services/metodos-procesos.jpg">
                                    <img src="simages/services/metodos-procesos.jpg" />
                                    <div class="mask"><i class="fa fa-search"></i></div>
                                </a>
                            </div>
                            <div class="servicebox-content">
                                <h3><a href="online-Consulting.html">ORGANIZACIÓN Y MÉTODOS</a></h3>
                                <p>Análisis, Evaluación, Organigrama, Funciones, Organización de Tareas, Estudios de Métodos de Trabajo, Manuales de Funciones y Procedimientos. </p>
                            </div>
                        </div>
                    </div>
					
                   <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                        <div class="single-servicebox">
                            <div class="servicebox-image">
                                <a class="lightbox-image" data-fancybox="gallery" href="simages/services/modelamiento-negocios.jpg">
                                    <img src="simages/services/modelamiento-negocios.jpg" />
                                    <div class="mask"><i class="fa fa-search"></i></div>
                                </a>
                            </div>
                            <div class="servicebox-content">
                                <h3><a href="online-Consulting.html">MODELAMIENTOS DE NEGOCIOS Y PROYECTOS</a></h3>
                                <p>Análisis, Planeamiento, Desarrollo y Seguimiento del Plan de Negocio y/o Proyecto.</p>
                            </div>
                        </div>
                    </div>	
					
                   <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                        <div class="single-servicebox">
                            <div class="servicebox-image">
                                <a class="lightbox-image" data-fancybox="gallery" href="simages/services/innovacion-tecnologia.jpg">
                                    <img src="simages/services/innovacion-tecnologia.jpg" />
                                    <div class="mask"><i class="fa fa-search"></i></div>
                                </a>
                            </div>
                            <div class="servicebox-content">
                                <h3><a href="online-Consulting.html">INNOVACIÓN, AUTOMATIZACIÓN Y TECNOLOGÍA</a></h3>
                                <p>Análisis de Requerimientos, Evaluación, Planificación e Implementación de Soluciones a Medida.</p>
                            </div>
                        </div>
                    </div>	
					
                   <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                        <div class="single-servicebox">
                            <div class="servicebox-image">
                                <a class="lightbox-image" data-fancybox="gallery" href="simages/services/certificaciones.jpg">
                                    <img src="simages/services/certificaciones.jpg" />
                                    <div class="mask"><i class="fa fa-search"></i></div>
                                </a>
                            </div>
                            <div class="servicebox-content">
                                <h3><a href="online-Consulting.html">CERTIFICACIONES Y HOMOLOGACIONES</a></h3>
                                <p>Análisis Situacional, Planificación, Implementación y Monitoreo de los procesos de Certificación y Homologación.</p>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
        <!--about-section end-->

       