  <!--Page Title-->
        <section class="page-title" style="background-image:url(simages/background/page-title-1.jpg);">
            <div class="auto-container">
                <h1>Servicios de Asesoría y Consultoría</h1>
			    <p style="color: #b9b4b4;">Para un mercado muy competitivo y de constantes cambios hemos desarrollado soluciones ágiles y flexibles</p>
            </div>
        </section>
        <!--Page Title end-->

        <!--Page Info-->
        <section class="page-info">
            <div class="auto-container clearfix">
                <div class="pull-left">
                    <h3></h3>
                </div>
                <div class="pull-right">
                    <ul class="bread-crumb clearfix">
                        <li><a href="/">Inicio</a></li>
                        <li>Servicios</li>
                    </ul>
                </div>
            </div>
        </section>
        <!--Page Info end-->

        <!--All Services-->
	
				
        <?=$Servicios;?>
        <!--about-section end-->
	
	    <?=$Indicadores;?>
		<!-- fact counter end -->
		

        <!-- Testimonial -->
		<?=$Testimonial;?>       

        <!-- Testimonial -->
		<?=$Clients;?>       

		<style>
		#Clientes img{
			transform-style: preserve-3d;
			width: 143px;
			margin: 59px 0px 0px 0px;			
		}
		</style>
