<div class="theme-layout">

	<div class="page-title style3" style="border-bottom:#c3c6c8 solid 2em;">
		<img src="/images/banners/equipo-de-ventas.jpg" alt="" />
	    <a href="/home#work" title="" style="color:#f86208;">PRODUCTOS <i class="fa fa-long-arrow-right" style="color:#f86208;"></i></a>
		<div class="container">
		<h1 style="color: #fffefd;">GESTIÓN DE VENTAS</h1>
		<p style="color:#f6d6a6;">La agilidad para proponer, ofertar, cerrar y monitorear <br>
		las ventas, es tu mayor ventaja.
		</p>		
		</div>
		
		<div>
			<a href="/home">
				<div class="logo" style="background-color: #fff;">
						<div style="padding: 0em 0.2em;">
							  <img src="/images/logo.jpg" alt="" width="25"/>
						</div>
						<div>
							 <span style="color:#2084c8;">Flex</span><span  style="color:#0bb8ce;">Zinn</span>
						</div>
				</div>		
			</a>		
		</div>				
	</div>

	<section>
		<div class="block less-spacing">
			<div class="container">
				<div class="row">
					<div class="col s12 m12 l12 column">
							<div class="big-title" style="margin-bottom:0px;">
								<div class="row">
										<div class="col s12 m12 l5">
										<h2>Sistema de Gestión Comercial<span>Proformas / Pedidos / Facturas</span></h2>
											
									</div>
									
									<div class="col s12 m12 l7">
										<span>Agilidad, flexibilidad, control y análisis</span>
										<p>Contamos con una solución a la medida de su negocio, es un sistema muy fácil de usar, es ideal para una empresa en crecimiento.
										Nuestra experiencia en estándares y en tecnología de gestión, nos permite brindarle un servicio de calidad y redituable.
										</p>
									</div>
								</div>
							</div><!-- Big Title -->
		                    <div class="tags-share" style="padding:0;">
								<div class="tags-share-inner">
									<div class="tags">
										<a href="#contact" title="" class="btnCall" style="background-color:#FF9800;border-color:#FF9800;">CONSULTAS EN LÍNEA</a>
									</div><!-- Tags -->
									<div class="share">
										<span>SHARE</span>
										<a href="#" title=""><i class="fa fa-facebook"></i></a>
									</div><!-- Share -->
								</div>
							</div><!-- Tags Share -->						
							
							<div class="col s12 m12 l12 column">
								<div class="related-posts">
									<div class="container">
										<div class="row">
											<div class="col s12 m12 l3">
												<h4 class="sub-title">Experiencia</h4>
											</div>
										
											
											<div class="col s12 m12 l9">
												<div class="related-carousel">
													<div class="blog-post">
														<div class="blog-img">
															<img src="/images/gestion_ventas/experiencia4.jpg" alt="" />
														</div>
														<span>SAP | ERP </span>
														<h3><a href="#" title="">SAP, es una solución ideal para empresas de gran envergadura. </a></h3>
													</div>
													<div class="blog-post">
														<div class="blog-img">
															<img src="/images/gestion_ventas/experiencia3.jpg" alt="" />
														</div>
														<span>SOFTLAND | ERP</span>
														<h3><a href="#" title="">SOFTLAND, es un sistema versatil y amigable para empresas en crecimiento</a></h3>
													</div>
													<div class="blog-post">
														<div class="blog-img">
															<img src="/images/gestion_ventas/experiencia1.jpg" alt="" />
														</div>
	                                                    <span>SICAR</span>
														<h3><a href="#" title="">SICAR, es el sistema ideal para una gestión mas automatizada</a></h3>
													</div>
													<div class="blog-post">
														<div class="blog-img">
																<img src="/images/gestion_ventas/experiencia2.jpg" alt="" />
														</div>
														<span>LISA | ERP</span>
														<h3><a href="#" title="">LISA, es una de las mejores cartas para extender su negocio</a></h3>
													</div>
												
												</div><!-- Related Carousel -->
											</div>
										</div>
									</div>
								</div>
							</div>

				
							<div class="big-title" style="margin-top: 50px;margin-bottom: 50px;">
								<div class="row">
									<div class="col s12 m12 l5"><h2>Módulos</span></h2></div>
								</div>
							</div><!-- Big Title -->
											
							<div class="single-portfolio-grids">
								<div class="row">
									<div class="col s12 m12 l12">
										<section>
											<div class="block" style="padding:0;">
												<div class="container">
													<div class="row">
														<div class="col s12 m12 l12 column">
															<div class="comments-sec">
																<div class="row">
																	<div class="col s12 m12 l9" style="width:100%;">
																		<div class="all-comments">
																			<ul>
																				<li>
																					<div class="comment">
																						<h5 class="comment-name">Cotizaciones</h5>
																						<span>Gestión y análisis</span>
																						<p>Incremente su capacidad de atención a más clientes, sin perder tiempo en cálculos y registros manuales. Cotice en diferentes monedas, indique la fecha de vigencia, etc.  </p>
																					</div><!-- Comment -->
																				</li>
																				<li>
																					<div class="comment">
																						<h5 class="comment-name">Pedidos</h5>
																						<span>Gestión y análisis</span>
																						<p>Controle los pedidos de sus clientes separando automáticamente la mercadería del almacén </p>
																					</div><!-- Comment -->
																				</li>
																				<li>
																					<div class="comment">
																						<h5 class="comment-name">Facturación</h5>
																						<span>Gestión y análisis</span>
																						<p>Emita sus comprobantes de pago (boletas, facturas, notas de credito, notas de débito) en dólares o moneda nacional, e imprima en sus propios formatos. 
																						Sus stocks se afectan automáticamente al registrar la venta. 
																						Puede facturar bienes o servicios indistintamente. Comisiones por vendedor o por zonas. Registro de Ventas comercial y contable bimoneda. </p>
																					</div><!-- Comment -->
																				</li>																				
																			</ul>

																			<div class="load-more-comments">
																				<a href="#" title=""><i class="fa fa-refresh"></i></a>
																			</div>
																		</div><!-- All Comments -->
																	</div>
																</div>
															</div>

														</div>
													</div>
												</div>
											</div>
										</section>

									</div>

								</div>
							</div><!-- Single Portfolio Grids -->

							
							
							<div class="single-portfolio-grids">
								<div class="row">
									<div class="col s12 m6 l4">
										<div class="portfolio-img">
											<img class="materialboxed" data-caption="A picture of some deer and tons of trees" src="/images/gestion_ventas/img_1.jpg" alt="" />
											<a href="#" title=""><i class="fa fa-plus"></i></a>
										</div><!-- Portfolio Image -->
									</div>
									<div class="col s12 m6 l4">
										<div class="portfolio-img">
											<img class="materialboxed" data-caption="A picture of some deer and tons of trees" src="/images/gestion_ventas/img_2.jpg" alt="" />
											<a href="#" title=""><i class="fa fa-plus"></i></a>
										</div><!-- Portfolio Image -->
									</div>
									<div class="col s12 m6 l4">
										<div class="portfolio-img">
											<img class="materialboxed" data-caption="A picture of some deer and tons of trees" src="/images/gestion_ventas/img_3.jpg" alt="" />
											<a href="#" title=""><i class="fa fa-plus"></i></a>
										</div><!-- Portfolio Image -->
									</div>
								</div>
							</div><!-- Single Portfolio Grids -->
								
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section id="contact">
		<div class="block no-padding">
			<div class="container">
				<div class="row">
					<div class="col s12 m12 l6 column">
						<div class="map">
							<div id="map-canvas"></div>
						</div>
					</div>
					<div class="col s12 m12 l6 offset-l6 column">
					    <?= $this->formContacto; ?>
						
					</div>
				</div>
			</div>
		</div>
	</section>	
</div>

