<div class="theme-layout">
	<div class="page-title style3" style="border-bottom:#229f3b solid 2em;">
		<img src="/images/banners/gestion_inventario.jpg" alt="" />
	    <a href="/home#work" title="" style="color:#fff;">PRODUCTOS <i class="fa fa-long-arrow-right" style="color:#fff;"></i></a>
		<div class="container">
		<h1 style="color:#f9faf8;"> INVENTARIOS</h1>
		<p  style="color:#d5f0d5;">A hora puedes conocer el stock <br> de tus productos  en tiempo real 
		
		</p>		
		</div>
		
		<div>
			<a href="/home">
				<div class="logo" style="background-color: #fff;">
						<div style="padding: 0em 0.2em;">
							  <img src="/images/logo.jpg" alt="" width="25"/>
						</div>
						<div>
							 <span style="color:#2084c8;">Flex</span><span  style="color:#0bb8ce;">Zinn</span>
						</div>
				</div>		
			</a>		
		</div>		
	</div>
	

	<section>
		<div class="block less-spacing">
			<div class="container">
				<div class="row">
					<div class="col s12 m12 l12 column">
							<div class="big-title" style="margin-bottom:0px;">
								<div class="row">
										<div class="col s12 m12 l5">
										<h2>Gestión de inventarios<span>Stocks/ Movimientos / Kardex</span></h2>
											
									</div>
									
									<div class="col s12 m12 l7">
										<span>Le brindamos agilidad, control, eficiencia en la entrega de sus productos</span>
										<p>Porque como usted sabemos de la importancia que conlleva el conocer de la disponibilidad, ubicación y el movimiento de un producto en el menor tiempo.
										</p>
									</div>
								</div>
							</div><!-- Big Title -->
		                    <div class="tags-share" style="padding:0;">
								<div class="tags-share-inner">
									<div class="tags">
										<a href="#contact" title="" class="btnCall">CONSULTAS EN LÍNEA</a>
									</div><!-- Tags -->
									<div class="share">
										<span>SHARE</span>
										<a href="#" title=""><i class="fa fa-facebook"></i></a>
									</div><!-- Share -->
								</div>
							</div><!-- Tags Share -->						
							
							<div class="col s12 m12 l12 column">
								<div class="related-posts">
									<div class="container">
										<div class="row">
											<div class="col s12 m12 l3">
												<h4 class="sub-title">EXPERIENCIA </h4>
											</div>
											<div class="col s12 m12 l9">
												<div class="related-carousel">
													<div class="blog-post">
														<div class="blog-img">
															<img src="/images/gestion_ventas/experiencia4.jpg" alt="" />
														</div>
														<span>SAP | ERP </span>
														<h3><a href="#" title="">SAP, es una solución ideal para empresas de gran envergadura. </a></h3>
													</div>
													<div class="blog-post">
														<div class="blog-img">
															<img src="/images/gestion_ventas/experiencia3.jpg" alt="" />
														</div>
														<span>SOFTLAND | ERP</span>
														<h3><a href="#" title="">SOFTLAND, es un sistema versatil y amigable para empresas en crecimiento</a></h3>
													</div>
													<div class="blog-post">
														<div class="blog-img">
															<img src="/images/gestion_ventas/experiencia1.jpg" alt="" />
														</div>
	                                                    <span>SICAR</span>
														<h3><a href="#" title="">SICAR, es el sistema ideal para una gestión mas automatizada</a></h3>
													</div>
													<div class="blog-post">
														<div class="blog-img">
																<img src="/images/gestion_ventas/experiencia2.jpg" alt="" />
														</div>
														<span>LISA | ERP</span>
														<h3><a href="#" title="">LISA, es una de las mejores cartas para extender su negocio</a></h3>
													</div>
												
												</div><!-- Related Carousel -->
											</div>
										
										</div>
									</div>
								</div>
							</div>

				
							<div class="big-title" style="margin-top: 50px;margin-bottom: 50px;">
								<div class="row">
									<div class="col s12 m12 l5"><h2>MÓDULOS</span></h2></div>
								</div>
							</div><!-- Big Title -->
											
							<div class="single-portfolio-grids">
								<div class="row">
									<div class="col s12 m12 l12">
										<section>
											<div class="block" style="padding:0;">
												<div class="container">
													<div class="row">
														<div class="col s12 m12 l12 column">
															<div class="comments-sec">
																<div class="row">
																	<div class="col s12 m12 l9" style="width:100%;">
																		<div class="all-comments">
																			<ul>
																				<li>
																					<div class="comment">
																						<h5 class="comment-name">UBICACIÓN Y PICKING</h5>
																						<span>Velocidad en las entradas y salidas</span>
																						<p>Mediante la ubicación de los productos y anaqueles, las empresas pueden analizar y rastrear activos fijos e inventarios con mayor precisión y eficiencia, esto genera gran capacidad en la 
																						gestión de salidas y entradas de los artículos.
                                                                                        </p>
																					</div><!-- Comment -->
																				</li>
																				<li>
																					<div class="comment">
																						<h5 class="comment-name">CODIFICACIÓN</h5>
																						<span>BARRAS, QR, NFC </span>
																						<p>La necesidad de saber la ubicación correcta de un activo demanda un sistema inteligente e integrado a otras tecnologías como la codificación de barras, QR y NFC.
                                                                                        </p>
																					</div><!-- Comment -->
																				</li>
																				<li>
																					<div class="comment">
																						<h5 class="comment-name">STOCKS</h5>
																						<span>En tiempo real</span>
																						<p>Porque sabemos lo determinante que es la disponibilidad o no de un producto para cerrar una venta, le ofrecemos un sistema inteligente y eficiente para lograr el
																						objetivo de: Propuestas de ventas, cierre de ventas, rotación de productos y una mejor atención al cliente.
                                                                                        </p>
																					</div><!-- Comment -->
																				</li>	
																				<li>
																					<div class="comment">
																						<h5 class="comment-name">KARDEX</h5>
																						<span>Movimientos de entredas y salidas </span>
																						<p>Tener una clara información de la rotación de productos en el tiempo, nos permitirá proyectar y antisiparnos al proceso de compras y ventas, también es vital conocer los costos 
																						de un artículo y sus variables en el tiempo.
																						Nuestro sistema le ayudará a gestionar y controlar los aspectos necesarios del KARDEX de sus almacenes.
																						</p>
																					</div><!-- Comment -->
																				</li>																					
																			</ul>

																			<div class="load-more-comments">
																				<a href="#" title=""><i class="fa fa-refresh"></i></a>
																			</div>
																		</div><!-- All Comments -->
																	</div>
																</div>
															</div>

														</div>
													</div>
												</div>
											</div>
										</section>

									</div>

								</div>
							</div><!-- Single Portfolio Grids -->

							
							
							<div class="single-portfolio-grids">
								<div class="row">
									<div class="col s12 m6 l4">
										<div class="portfolio-img">
											<img class="materialboxed" data-caption="A picture of some deer and tons of trees" src="/images/gestion_inventarios/slideB1.jpg" alt="" />
											<a href="#" title=""><i class="fa fa-plus"></i></a>
										</div><!-- Portfolio Image -->
									</div>
									<div class="col s12 m6 l4">
										<div class="portfolio-img">
											<img class="materialboxed" data-caption="A picture of some deer and tons of trees" src="/images/gestion_inventarios/slideB2.jpg" alt="" />
											<a href="#" title=""><i class="fa fa-plus"></i></a>
										</div><!-- Portfolio Image -->
									</div>
									<div class="col s12 m6 l4">
										<div class="portfolio-img">
											<img class="materialboxed" data-caption="A picture of some deer and tons of trees" src="/images/gestion_inventarios/slideB3.jpg" alt="" />
											<a href="#" title=""><i class="fa fa-plus"></i></a>
										</div><!-- Portfolio Image -->
									</div>
				
								</div>
							</div><!-- Single Portfolio Grids -->
								
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	
	<section id="contact">
		<div class="block no-padding">
			<div class="container">
				<div class="row">
					<div class="col s12 m12 l6 column">
						<div class="map">
							<div id="map-canvas"></div>
						</div>
					</div>
					<div class="col s12 m12 l6 offset-l6 column">
					    <?= $this->formContacto; ?>
						
					</div>
				</div>
			</div>
		</div>
	</section>		
	
</div>

