
        <!-- testimonial -->
        <section class="hometestmon">
            <div class="container">
                <div class="sec-title text-center">
                    <h2>Clientes Satisfechos</h2>
                    <p>Nuestra filosofía de servicio genera lazos perdurables con cada uno de nuestros clientes.</p>
                    <span class="colorborder"></span>
                </div>

                <div class="row testmonrow">
                    <div class="col-sm-6">
                        <div class="testwrp">
                            <div class="single-testm">
                                <div class="client-image"><img src="simages/clients/gian_carlo.jpg" class="testmimg" alt="" width="100%" > </div>
                                <p>Ejecutivo senior con sólida experiencia en Marketing, Customer Experience y Product 
								Management. Cuenta con 19 años en la industria financiera en compañías globales y líderes 
								del mercado.
								CEO de la empresa Adn | ENDO.MARKETING | Perú </p>
                                <h4>Gian VillaNueva <small>CEO</small></h4>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="testwrp">
                            <div class="single-testm">
                                <div class="client-image"><img src="simages/clients/daniel_ponte.jpg" class="testmimg" alt="" width="100%"> </div>
                                <p>Ejecutivo senior con amplia experiencia en los mercados de Europa y Latinoamérica, especialista en Marketing OffLine, Marketing OnLine, Ventas, Finanzas y Estrategia Coorporativa. 
								CEO de la empresa WexPAGE | España
								</p>
                               
                                <h4>Daniel Ponte<small>CEO</small></h4>
                            </div>
                        </div>
                    </div>					
                </div>
            </div>
        </section>
        <!-- testimonial end -->